config/routes.rb
Rails.application.routes.draw do
  get 'chat/index'
  get 'chat/logs'
  post 'chat/say'
  root "chat#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :_set_redis, only: [:say]
  before_action :_set_root_path, only: [:logs]

  def index
  end

  def say
    @start = params[:start] == 'true'
    @name = params[:name]
    @message = params[:message]
    @response = _megahal
    respond_to do |format|
      format.turbo_stream
    end
  end

  def logs
    file = params[:file]
    if file.present?
      path = File.join(@root_path, "log", file)
      @lines = File.readlines(path).map(&:strip)
    else
      @files = Dir[File.join(@root_path, "log", "megahal*log")].map do |path|
        File.basename(path)
      end
    end
  end

  private

  def _megahal
    epoch = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    key = "megahal-message:#{SecureRandom.uuid}"
    data = { time: Time.now.to_f, name: @name, message: @message }
    @redis.set(key, data.to_json)
    key.gsub!("-message:", "-reply:")
    while Process.clock_gettime(Process::CLOCK_MONOTONIC) - epoch < 10
      reply = @redis.getdel(key)
      return reply if reply.present?
      sleep 0.1
    end
    key.gsub!("-reply:", "-message:")
    @redis.del(key)
    return "[TIMEOUT]"
  end

  def _set_redis
    @redis = Redis.new(url: ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" })
  end

  def _set_root_path
    @root_path = ENV.fetch("MOUNT_PATH") { Rails.root.to_s }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/views/chat/_file.html.erb
<p class="text-yellow-500">
  <a href="?file=<%= file %>"><%= file %></a>
</p>

app/views/chat/_line.html.erb
<p class="text-gray-300">
  <tt><%= line %></tt>
</p>

app/views/chat/index.html.erb
<div class="flex flex-col h-screen w-screen overflow-hidden">
  <nav class="sticky top-0 bg-gray-700 p-3 drop-shadow">
    <h1 class="text-gray-300 text-2xl text-center">MegaHAL</h1>
  </nav>

  <main class="bg-black h-screen overflow-y-scroll p-5 text-xl">
    <%= turbo_frame_tag "messages" do %>
      <p class="text-yellow-500">(MegaHAL joins the chat)</p>
    <% end %>
  </main>

  <footer class="bg-gray-800 h-30 p-5">
    <%= turbo_frame_tag "chat" do %>
      <%= form_with url: chat_say_path, data: { controller: "name", action: "turbo:submit-start->name#echo submit->name#check" } do |form| %>
        <%= form.hidden_field :start, value: true %>
        <%= form.text_field :name, placeholder: "What is your name, human?", class: "w-full rounded-lg text-2xl bg-gray-700 text-white p-1 focus:outline-0" %>
      <% end %>
    <% end %>
  </footer>
</div>
<%= turbo_stream_from "chat" %>

app/views/chat/logs.html.erb
<div class="flex flex-col h-screen w-screen overflow-hidden">
  <nav class="sticky top-0 bg-gray-700 p-3 drop-shadow">
    <h1 class="text-gray-300 text-2xl text-center">MegaHAL Logs</h1>
  </nav>

  <main class="bg-black h-screen overflow-y-scroll p-5 text-lg">
    <%= render partial: "file", collection: @files %>
    <%= render partial: "line", collection: @lines %>
  </main>
</div>

app/views/chat/say.turbo_stream.erb
<turbo-stream action="append" target="messages">
  <template>
    <p class="text-white">MegaHAL: <%= @response %></p>
  </template>
</turbo-stream>

<turbo-stream action="replace" target="chat">
  <template>
    <%= form_with url: chat_say_path, data: { controller: "chat", action: "turbo:submit-start->chat#echo turbo:before-fetch-response->chat#enable" } do |form| %>
      <%= form.hidden_field :name, value: @name %>
      <%= form.text_field :message, placeholder: "Say something!", class: "w-full rounded-lg text-2xl bg-gray-700 text-white p-1 focus:outline-0" %>
    <% end %>
  </template>
</turbo-stream>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MegaHAL</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>